CREATE TABLE `course` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`colour` VARCHAR(10),
	`icon` VARCHAR(20)
);

CREATE TABLE `course_item` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`course_id` INT(20) NOT NULL,
	`title` VARCHAR(100) NOT NULL,
	`content_type` INT(1) NOT NULL
);

CREATE TABLE `course_content` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`course_id` INT(20) NOT NULL,
	`name` VARCHAR(100) NOT NULL
);